### ISSUE TITLE
Ways to avoid memory crash?

### ISSUE THREAD

**Issue by gfelitti** [AlertaDengue/PySUS#11] opened 2019-04-11 01:21 UTC
This is more of a doubt than an issue. When I try to load a +60 MB DBC file using PySUS, the 16 GB RAM are not enough and my desktop crashes. Considering I'm used to work smoothly with  +3 million lines DataFrames in it, is there something I could do to avoid the crash with PySUS? I considered using multiprocessing, Is this feasible? Thank you

**Comment by fccoelho** [comment] 2019-04-11 11:22
Could you paste here the exact lines you are running so that I can try to reproduce the problem?

I routinely open large DBC, for example a full year of SIASUS for the state of MG in which each month is 60 to 70MB in size without problems.

if you have already downloaded this file once, it should be cached in the pysus directory as a parquet file.

You can then try to load it directly from the the parquet cache, to  check if the memory issues are with pysus code. Here is how you do it(with an example file I have in my desktop):

```python
pd.read_parquet('SIA_PAMG1705_.parquet')
```

**Comment by gfelitti** [comment] 2019-04-11 19:18
Sure. It's the most simple code:

`from pysus.utilities.readdbc import read_dbc
df = read_dbc("BIMG1702.dbc", encoding='iso-8859-1')`

I tried to find the parquet, but the systems crashes before is capable of creating it.

I'm on a Ubuntu machine. I will try on a Windows one.

**Comment by fccoelho** [comment] 2019-04-11 20:55
Which version of `Python`, `Pandas` and `readdbf` do you have installed?

I have applied a memory profileron the following code:
```python
In [17]: %%memit 
    ...: df = read_dbc('DNRJ2014.dbc', encoding='iso-8859-1')
peak memory: 3276.18 MiB, increment: 127.91 MiB
```
This `dbc` is 12MB and the corresponding `dbf` is 57MB so the memory used is roughly twice the size.

As a workaround try to use dbc2dbf:
```python
>>> from pysus.utilities.readdbc import dbc2dbf
>>> dbc2dbf('DNRJ2014.dbc', 'DNRJ2014.dbf')
```
This will convert the file directly to dbf without creating a pandas dataframe.

**Comment by fccoelho** [comment] 2019-04-11 21:07
By the way, the `read_dbc` does not create a parquet file, only the download functions from the modules SIS, SIH, SIM, etc

**Comment by gfelitti** [comment] 2019-04-11 23:16
PySUS==0.3.7
Pandas = 0.24.1
Python 3.7.2

Based in your suggestion, I was able to transform the DBC to a DBF and used the simpledbf module to convert it to CSV. Finally, it loaded on Pandas. It puts some extra steps on the process, but I'm ok with it.

That's why I didn't find the parquest - I'm downloading all the files using a script I wrote.

Thanks for your help.

**Comment by fccoelho** [comment] 2019-04-12 12:13
Good. Since I could not reproduce the problem I am closing this issue for now.

**Closed by fccoelho** 2019-04-12 12:13 UTC
Labels: question
